### ISSUE TITLE
Version pattern not compatible with SBT dependency resolver

### ISSUE THREAD

**Issue by wmeints** [noorq/casser#1]
Hi, I noticed that you have used _2.11 in the version of the package. I think this has to do with the scala-library you're using. However, if you put the _2.11 in the version instead of the artifact name you can't use the library with SBT like you would with all other scala based packages.

The sample below doesn't work:

```
libraryDependencies ++ = {
  Seq(
    "com.noorq.casser" %% "casser-core" % "1.1.0"
  )
}
```

May I suggest you move the _2.11 postfix to the artifact name, so that I can use the package as intended from SBT?

**Comment by alexshvid** [comment]
Interesting question, I am not using casser directly in scala project, but if needed it is no problem to do this change.
Let's do artifact casser-core-2.11 and problem will be solved.
Feel free to create a pull request or I will do it by myself.

**Comment by wmeints** [comment]
Thanks for the quick response! I think I got time tomorrow to make the pull request.
